### ISSUE TITLE
profvis in modularized shiny app

### ISSUE THREAD

**Issue by ardeeshany** [r-lib/profvis#101]
Hi Winston,

I have a nested modularized shiny app and it seems the `profvis()`  just show the time of all modules in the initial run, but when I change the modules, it does not record anythings. The style of my code is like this : 

`

             library(...)
             source(modules)

             ui <- dashboardPage(
             HeaderUI("mod_header"),                   
             SidebarUI("mod_sidebar"),
             BodyUI("mod_body",theme=theme_RAAVI))

            server <- function(input, output,session) {      
            callModule(Header,"mod_header")
            callModule(Sidebar,"mod_sidebar")
            callModule(Body,"mod_body")}

            shinyApp(ui=ui,server=server)
 

and in Body I have 4 modules all of them includes some modules in a tabsetPanel format.

**Comment by hadley** [comment]
I'm going to close this because I presume you have figured out a fix in the last 6 (!!) years.
