### ISSUE TITLE
Profvis with > 1 interval

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/profvis#103]
I'm profiling a function that takes a very long time to return (2-3 minutes). I wanted to set the sampling interval to 1 second so that the profiler doesn't interrupt the execution much. However, setting interval to any number greater than 1 causes a fatal error, forcing R to quit

```
> require(profvis)
Loading required package: profvis
> profvis(1:10000, interval = 1)
Fatal error: setting profile timer failed
```

**Comment by hadley** [comment]
This seems to work ok for me (6 years later 😆)

``` r
profvis::profvis(1:1e6, interval = 1)
#> Error in parse_rprof_lines(lines, expr_source): No parsing data available. Maybe your function was too fast?
```

<sup>Created on 2024-08-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
