### ISSUE TITLE
Cannot zoom out in the flame graph

### ISSUE THREAD

**Issue by Saren-T** [r-lib/profvis#137]
I can zoom in but I cannot zoom out anymore. Anything, which runs later, I need to manually drag the graph, which takes ages... I wonder, what the reasoning behind the zoom out limit was? But it is unusable as it is now for long running code such as Shiny apps.
![image](https://user-images.githubusercontent.com/90200087/174277913-c9271491-6f22-4b4a-af75-cf5caaf4cfc5.png)

**Comment by hadley** [comment]
Can you provide more information about the problem? I currently don't understand it.
