### ISSUE TITLE
How to run profvis so it show runtime for each line of a function from a package without rewriting the function as input?

### ISSUE THREAD

**Issue by garyzhubc** [r-lib/profvis#145]
Right now it seems like profvis requires re-writing the function

`profvis({fun<-function(...) { ... return(...) } })`

But if we only pass the function evaluation to profvis it will compress the whole function into one line

`profvis(fun(...))`

Is there a way to profile the function line by line without re-writing the whole script as input?

**Comment by wch** [comment]
Yes. The code needs to be sourced with source refs. If your are using `source("file.R")` in an interactive session, it should be loaded with source refs.

If the function is in a package, see this for information on how to load it with source refs: https://rstudio.github.io/profvis/faq.html#how-do-i-get-code-from-an-r-package-to-show-in-the-code-panel
