### ISSUE TITLE
Pandoc "out of memory" error when using profvis and haven

### ISSUE THREAD

**Issue by AHoerner** [r-lib/profvis#67]
Dear Folks--
I am reading a set of .dta files containing Census/BLS Current Population Survey data, formatted as Stata .dta files, using haven. I have code that reads 15 of these files, saving each and then deleting them to conserve memory. The input .dta files ranged from 0.5 to 2.0 GB. I ran this code, copied below, wrapped in the profvis function. 

haven successfully (I think, not yet having made a detailed examination) transformed all the .dta files, and my code successfully saved those files to disk. However, profvis failed, in the following manner:

The size of the editor window in RStudio maxed out, hiding the console, but was blank.
When i resized the window, i found this error message on the console:
"pandoc.exe: out of memory
 Warning message:
 running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS "C:\Users\hack the hood\Dropbox\R_PROJ \fairR.Rproj.user\2F905F92\profiles-cache\file172825dc4013.html" --from markdown --output "C:\Users\hack the hood \Dropbox\R_PROJ\fairR.Rproj.user\2F905F92\profiles-cache\file172825dc4013.html" --self-contained --template C:\Users \HACKTH~1\AppData\Local\Temp\RtmpG6NoJl\file1728c1b6059.html' had status 1 
"
Any assistance on resolving this problem greatly appreciated
I ran this code under Windows 7, R 3.3.1, RStudio 0.99.1251, and the currant version of haven.

Andrew Hoerner
TowardVictory@gmail.com
###### 
# ConvertDta reads a list of Stata-formatted (.dta) file names (as a char vector
# and converts each to a data frame, saves it, and removes it (to conserve
# memory)
###### 

ConvertDta <- function(pathIn = NULL, namesIn, namesOut, pathOut = NULL){
  library(haven)
  dtaMemory <- numeric(length(namesIn))
  if(is.null(pathIn))  {pathIn  <-""}
  names(dtaMemory) <- namesOut
  namesIn  <- paste0(pathIn,  namesIn)
  if(is.null(pathOut)) {pathOut <-""}
  pathNamesOut <- paste0(pathOut, namesOut)

  for (ii in seq_along(namesIn)){
    assign(namesOut[[ii]], read_dta(namesIn[[ii]]))
    dtaMemory[[ii]] <- object.size(get(namesOut[[ii]]))
    print(c("Size of ", names(dtaMemory)[[ii]], ": ", dtaMemory[[ii]]))
    save(list = namesOut[[ii]], file = pathNamesOut[[ii]])
    rm(list = namesOut[[ii]])
  }
  out <- dtaMemory
}
###### 
# Make arguements for ConvertDta

pathIn  <- "C:/Users/hack the hood/fairR LOCAL/dta files 6.0GB/"
pathOut <- "C:/Users/hack the hood/fairR LOCAL/dta files 6.0GB/"

prefix  <- "cps_00"
middle  <- c("093", "094", "096", "097", "098", "099", "100", "101", "102",
             "103", "104", "105", "106", "107")

suffix  <- ".dta"

fileNamesIn <- paste0(prefix, middle, suffix)
fileNamesIn

suffix  <-".df"  # only suffix is different.
fileNamesOut<- paste0(prefix, middle, suffix)
fileNamesOut
###### 
# ProfileVis is a simple wrapper for Hadley Wickham's profiling package profvis
###### 

ProfileVis <- function(rscript){
  library(profvis)
  profvis({rscript
  })
}

**Comment by AHoerner** [comment]
Ran a modified version of my code on 12 GB of .dta files, ranging in size from 200 MG to 1.3 GB. Haven successfully converted all of them, on a five-year old Windows 7 machine with 4 GB of RAM. (Took an  hour and 3 min). It is interesting to observe how inefficient the .dta storage format is. As saved data frames -- tibbles, actually -- they were only 1.5 GB -- an eighth of the space.

 However profvis failed again, with a similar error message, reproduced below:

pandoc.exe: out of memory
Warning message:    running command '"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS "C:\Users\hack the hood\Dropbox\R_PROJ\fairR\.Rproj.user\2F905F92\profiles-cache\file1d7838456be4.html" --from markdown --output "C:\Users\hack the hood\Dropbox\R_PROJ\fairR\.Rproj.user\2F905F92\profiles-cache\file1d7838456be4.html" --self-contained --template C:\Users\HACKTH~1\AppData\Local\Temp\RtmpwjprAR\file1d7872d840cf.html' had status 1

**Comment by AHoerner** [comment]
Ooops!! Forgot to add:
Curent R, RStudeo, haven, profvis. And here is my session info:
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_0.2.1    pryr_0.1.2     profvis_0.3.2  ggplot2_2.1.0  dplyr_0.5.0   
[6] fortunes_1.5-3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6      codetools_0.2-14 digest_0.6.10    assertthat_0.1  
 [5] grid_3.3.1       R6_2.1.3         plyr_1.8.4       jsonlite_1.0    
 [9] gtable_0.2.0     DBI_0.5          magrittr_1.5     scales_0.4.0    
[13] stringi_1.1.1    tools_3.3.1      stringr_1.1.0    htmlwidgets_0.7 
[17] munsell_0.4.3    yaml_2.1.13      colorspace_1.2-6 htmltools_0.3.5 
[21] tibble_1.2      
>

**Comment by VT-SCM** [comment]
Is there an answer to this issue? I've encountered the same thing. It looks like profvis consumes a large amount of memory, more than 2GB memory limit on Windows.

**Comment by lao8n** [comment]
I also have a similar issue with profvis and the pandoc.exe out of memory (and I too am trying to benchmark .dta files to dataframes conversion)

**Comment by hadley** [comment]
I'm going to close this under the assumption that you have figured out a solution in the last 8 (!!) years!
