### ISSUE TITLE
Running time under-estimated with parallel::parLapply()

### ISSUE THREAD

**Issue by pierucci** [r-lib/profvis#70]
It seems the total running time is greatly underestimated when `profvis()` is used on code using `parallel::parLapply()`. See the following example:

``` r
newdata <- as.data.frame(matrix(rnorm(10 * 1e4), nrow = 1e4))
pnewdata <- split(newdata, rep(1:2, each = 5e3))

f <- function(x) {
  # inefficient on purpose
  for(i in seq_len(nrow(x))) {
    res <- numeric(nrow(x))
    res[i] <- sum(x[i, ])
  }
  mean(res)
}

cl <- parallel::makeCluster(2)

system.time(parallel::parLapply(cl, pnewdata, f))
#>    user  system elapsed 
#>   0.068   0.016   3.370

profvis::profvis(parallel::parLapply(cl, pnewdata, f))
# only a few ms of total time

parallel::stopCluster(cl)
```

```
Session info --------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.44)    
```

**Comment by beansrowning** [comment]
@pierucci From what I understand, profvis is only going to be able to monitor the R process where profvis was evaluated which is separate from your cluster workers. I'm not sure if there is a way around this with the profvis framework at the present, though maybe someone knows better.

**Comment by Gronnesby** [comment]
I've seen the same issue using BioCParallel. From what I can tell, the profiler only considers the main thread. Which means that any thread/process spawned from the main rsession process, will not be accounted for in the execution time. Only the thread that spawns the workers are timed, and I am guessing that it is idle/not running for most of the execution time.

The same problem seems to apply for `Rprof` as well (not sure if profvis uses this or not). I ran a script that took well over a minute, but the output from `Rprof` is not able to time it:

```
$by.total
                          total.time total.pct self.time self.pct
"eval"                          0.42    100.00      0.00     0.00
"source"                        0.42    100.00      0.00     0.00
"withVisible"                   0.42    100.00      0.00     0.00

```

**Comment by johncassil** [comment]
This appears to still be a big issue. 

It looks like when code is processed in parallel, profvis will show a call as taking 10ms, when microbenchmark and bench will show it taking 500ms.

**Comment by hadley** [comment]
profvis now defaults to tracking real time, so this is now much improved.
