### ISSUE TITLE
Split parsing code to a separate package

### ISSUE THREAD

**Issue by krlmlr** [r-lib/profvis#74]
Would you support moving the parse_rprof() function to a separate package and exporting it, and make profvis() also accept parsed output? This would allow to use profvis for profiling data from other sources (via extensions to the new package).

**Comment by wch** [comment]
What other kinds of sources do you have in mind?

If it's possible to keep it in profvis, I'd prefer that. In the past we've changed the format of the output of `parse_rprof()`, and I'd prefer not to deal with the headache of having the packages get out of sync.

**Comment by krlmlr** [comment]
Thanks. I'm thinking about profilers for languages other than R.

How about defining a class and a stable-ish API for the output? I guess this would give even fewer headaches in the long run.

**Comment by wch** [comment]
That sounds reasonable.

One thing we might want to do in the future is add support for timestamps (#72), so that's something we'd want to keep in mind.

**Comment by hadley** [comment]
Given that we havne't
