### ISSUE TITLE
Filter out compiler frames

### ISSUE THREAD

**Issue by para2x** [r-lib/profvis#78]
Hey guys,
I'm using 'profvis' to find the bottleneck of my big, fat shiny app. I have several ObserveEvents in my code and when I run the profvis, it just tells that there are two of ObservEvents that they are taking the most time. How can I find out which one them are these referring to ? When hover over those ObserveEvenehandlers in the report the labels do not match with the labels I set for each observevent function in the code.

![capture](https://cloud.githubusercontent.com/assets/7999941/26036461/672bdf30-389b-11e7-93a1-0a67dbc1f826.PNG)

**Comment by wch** [comment]
Have you tried unchecking the "Hide internal function calls" option? That might help.

It looks like all the time for those two observeEvents is spent by R compiling the code. That's what the `tryCmpfun` is. In R 3.4.0, the byte code compiler is enabled by default.

It's possible that we need to revisit the way that call stacks get displayed for the new compiler behavior, and for observeEvents in general.

**Comment by para2x** [comment]
It turned out simply using "ignoreNULL = TRUE" and  "ignoreInit = TRUE", I could solve my problem. But It could be nice if labels in profvis results were matched with labels set for observe/obserevent functions.
Thank you anyways

**Comment by hadley** [comment]
Closing this because it's 7 years old 😄
