### ISSUE TITLE
digest() times are attributed to other functions

### ISSUE THREAD

**Issue by wch** [r-lib/profvis#96]
When calling `digest::digest()`, sometimes the times can be attributed to other functions. This is likely due to something funny in the R profiler itself, but I'm filing it here to track it.

To start, this example correctly attributes the time spent in `digest()`, about 700ms on my machine:

```R
profvis::profvis({
  x <- list(1,2,3)
  for (i in 1:5000) {
    digest::digest(x)
  }
})
```

![image](https://user-images.githubusercontent.com/86978/40140702-8ccc7aa4-5921-11e8-9dfb-ccafb9c52579.png)

If you profile `file.exists()`, it's much faster -- this takes about 10ms on my machine:

```R
profvis::profvis({
  for (i in 1:5000) {
    file.exists("abcd")
  }
})
```

However, if the `digest()` is followed by `file.exists()`, profvis says that most of the time is spent in `file.exists()`:

```R
profvis::profvis({
  x <- list(1,2,3)
  for (i in 1:5000) {
    digest::digest(x)
    file.exists("abcd")
  }
})
```

![image](https://user-images.githubusercontent.com/86978/40140596-5aac030a-5921-11e8-9324-68a44b93a5ce.png)

If the Rprof output is saved with the `prof_output` arg, most of the lines do indeed say that they're in `file.exists()`.

*****

```
─ Session info ────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 os       macOS High Sierra 10.13.4   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-05-16                  

─ Packages ────────────────────────────────────────────────────────────────────────────────
 package     * version date       source        
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.4.0)
 digest        0.6.15  2018-01-28 cran (@0.6.15)
 htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)
 htmlwidgets   1.2     2018-04-19 CRAN (R 3.4.4)
 jsonlite      1.5     2017-06-01 CRAN (R 3.4.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)
 profvis       0.3.5   2018-02-22 CRAN (R 3.4.3)
 Rcpp          0.12.16 2018-03-13 CRAN (R 3.4.4)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.4.1)
 stringi       1.1.7   2018-03-12 CRAN (R 3.4.4)
 stringr       1.3.0   2018-02-19 cran (@1.3.0) 
 withr         2.1.2   2018-03-15 CRAN (R 3.4.4)
 yaml          2.1.18  2018-03-08 CRAN (R 3.4.4)
```

**Comment by lionel-** [comment]
`digest()` seems to be I/O bound, perhaps because it is implemented on top of the serialiser. With real-time sampling (https://github.com/lionel-/r-source/commit/be4d420118078eb27ed8561ca4a9a42f7c4f04a4) and aggregated output we get: 
![Screenshot 2020-12-07 at 17 51 45](https://user-images.githubusercontent.com/4465050/101379802-fb850680-38b4-11eb-9fbc-7821cbfb50c3.png)

**Comment by hadley** [comment]
I can confirm @lionel-'s findings that this now looks fine.
